(define p (cons 1 2))
p
(car (list 1 2 3))
(cdr (list 1 2 3))
(eq? 1 1)
(eq? "ab" "ab")
(null? (list))
(boolean? #t)
(symbol? (string->symbol "abc"))
(integer? 12)
(string? "ab")
(pair? (list 1))
(procedure? +)
(number->string 123)
(string->number "456")
(symbol->string (string->symbol "hello"))
(string->symbol "hi")
